
package at.campus02.mul.lotto;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LottoService", targetNamespace = "http://lotto.mul.campus02.at/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LottoService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://lotto.mul.campus02.at/LottoService/predictNumbers")
    @WebResult(name = "predictNumbersResponse", targetNamespace = "http://lotto.mul.campus02.at/", partName = "parameters")
    public String predictNumbers();

}
