
package at.campus02.mul.lotto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LottoService", targetNamespace = "http://lotto.mul.campus02.at/", wsdlLocation = "file:/D:/dev/workspaces/bla/HelloJAXWS/src/at/campus02/mul/lotto/wsdl/lottoservice.wsdl")
public class LottoService_Service
    extends Service
{

    private final static URL LOTTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOTTOSERVICE_EXCEPTION;
    private final static QName LOTTOSERVICE_QNAME = new QName("http://lotto.mul.campus02.at/", "LottoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/workspaces/bla/HelloJAXWS/src/at/campus02/mul/lotto/wsdl/lottoservice.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOTTOSERVICE_WSDL_LOCATION = url;
        LOTTOSERVICE_EXCEPTION = e;
    }

    public LottoService_Service() {
        super(__getWsdlLocation(), LOTTOSERVICE_QNAME);
    }

    public LottoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOTTOSERVICE_QNAME, features);
    }

    public LottoService_Service(URL wsdlLocation) {
        super(wsdlLocation, LOTTOSERVICE_QNAME);
    }

    public LottoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOTTOSERVICE_QNAME, features);
    }

    public LottoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LottoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LottoService
     */
    @WebEndpoint(name = "LottoServicePortBinding")
    public LottoService getLottoServicePortBinding() {
        return super.getPort(new QName("http://lotto.mul.campus02.at/", "LottoServicePortBinding"), LottoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LottoService
     */
    @WebEndpoint(name = "LottoServicePortBinding")
    public LottoService getLottoServicePortBinding(WebServiceFeature... features) {
        return super.getPort(new QName("http://lotto.mul.campus02.at/", "LottoServicePortBinding"), LottoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOTTOSERVICE_EXCEPTION!= null) {
            throw LOTTOSERVICE_EXCEPTION;
        }
        return LOTTOSERVICE_WSDL_LOCATION;
    }

}
